import type { Readable } from 'node:stream';
import { sql, type Kysely, type Transaction } from 'kysely';
import type { Redis } from 'ioredis';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { S3Client } from '@aws-sdk/client-s3';
import { Upload } from '@aws-sdk/lib-storage';
import type { Logger } from 'pino';
import type { DB } from '@skaly/shared';
import type { Role, SignupRequestInput } from '@skaly/shared/schemas/auth';
import { AttendanceService } from './AttendanceService.js';

/**
 * Domain error carrying the HTTP status the route should surface. Routes map
 * `code` straight onto the error envelope; `statusCode` drives the response.
 */
export class AuthError extends Error {
  constructor(
    public readonly code: string,
    public readonly statusCode: number,
    message: string,
  ) {
    super(message);
    this.name = 'AuthError';
  }
}

/**
 * Shape Sprint 2's real AuditService.log will accept. Kept identical here so
 * swapping the placeholder for the real service is a one-line change.
 */
export interface AuditLogEntry {
  actorId: string;
  /** Origin of the action (audit C-04). Web requests are 'web'. */
  actorSource?: 'web' | 'system' | 'cron';
  entity: string;
  entityId: string;
  action: string;
  before?: unknown;
  after?: unknown;
  trx?: Transaction<DB>;
}

// 5-minute TTL, matching the auth plugin's staff_lookup cache (STEP 4).
const STAFF_CACHE_TTL_SECONDS = 300;
const staffCacheKey = (supabaseUid: string) => `staff_lookup:${supabaseUid}`;

export interface CreateInviteParams {
  /** Required — every invite is scoped to a specific address (APPFLOW §2.7). */
  email: string;
  role: Role;
  createdBy: string;
  /** Reuse an outer transaction when the caller already opened one. */
  trx?: Transaction<DB>;
}

export interface ConsumeInviteSignupParams {
  token: string;
  password: string;
  name: string;
  dateOfBirth: string; // ISO YYYY-MM-DD
  mobileNumber: string;
}

/** A CV upload handed to the service as a stream — never buffered to memory. */
export interface CvUpload {
  stream: Readable;
  mimetype: string;
}

/** Allow-list of CV content types and their canonical file extensions. */
const CV_MIME_EXT: Record<string, string> = {
  'application/pdf': 'pdf',
  'application/msword': 'doc',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document': 'docx',
};

/**
 * Shape Sprint 2's real NotificationService.create will accept. Placeholder
 * for now (logs intent) — swap-in is one line, same pattern as the audit log.
 */
export interface NotificationCreateEntry {
  recipientId: string;
  type: string;
  title: string;
  data?: unknown;
}

export class AuthService {
  private readonly attendance = new AttendanceService();

  constructor(
    private readonly db: Kysely<DB>,
    private readonly redis: Redis,
    private readonly supabaseAdmin: SupabaseClient,
    private readonly logger: Logger,
    private readonly s3: S3Client,
    private readonly r2Bucket: string,
  ) {}

  /**
   * Placeholder for Sprint 2's AuditService.log. Emits the entry to the log
   * with the same arg shape the real service will take. `trx` is intentionally
   * dropped from the logged payload (it is not serialisable).
   */
  private auditServiceLog(entry: AuditLogEntry): void {
    const { trx: _trx, ...rest } = entry;
    void _trx;
    this.logger.info({ audit: rest }, 'audit');
  }

  /**
   * Placeholder for Sprint 2's NotificationService.create — logs the intent
   * with the same arg shape the real service will take.
   */
  private notificationServiceCreate(entry: NotificationCreateEntry): void {
    this.logger.info({ notification: entry }, 'notification');
  }

  /**
   * Create an invite link and (when email-scoped) send the Supabase invite
   * email. Runs in one transaction — reuses `trx` if the caller passed one.
   */
  async createInvite(params: CreateInviteParams): Promise<{
    id: string;
    token: string;
    expiresAt: Date;
    email: string;
    role: string;
  }> {
    const { email, role, createdBy } = params;

    const run = async (trx: Transaction<DB>) => {
      // a/b. Insert; token + expires_at are generated by the table defaults.
      const row = await trx
        .insertInto('invite_links')
        .values({ email, role, created_by: createdBy })
        .returning(['id', 'token', 'expires_at', 'role'])
        .executeTakeFirstOrThrow();

      // c. Create the Supabase user + send the branded invite email in one
      // step. Our token rides along in user_metadata so /signup/invite can
      // match it. The created user has no password yet — signup sets it.
      // We persist the user's UUID on the invite so signup can resolve it
      // from the token alone (the [Copy link] fallback in APPFLOW §2.7 shares
      // this same token URL manually if the email itself doesn't arrive).
      const { data, error } = await this.supabaseAdmin.auth.admin.inviteUserByEmail(email, {
        data: { invite_token: row.token },
      });
      if (error || !data?.user) {
        // Invite is only valid once the Supabase user exists; roll back.
        throw new AuthError('INVITE_EMAIL_FAILED', 502, 'Could not send the invite email.');
      }
      await trx
        .updateTable('invite_links')
        .set({ supabase_uid: data.user.id })
        .where('id', '=', row.id)
        .execute();

      // d. Audit (placeholder until Sprint 2).
      this.auditServiceLog({
        actorId: createdBy,
        entity: 'invite_link',
        entityId: row.id,
        action: 'invite.create',
        after: { email, role },
        trx,
      });

      return {
        id: row.id,
        token: row.token,
        expiresAt: new Date(row.expires_at as unknown as string),
        email,
        role: row.role,
      };
    };

    return params.trx ? run(params.trx) : this.db.transaction().execute(run);
  }

  /**
   * Consume an invite token: validate it, set the password on the Supabase user
   * that was created at invite time, create the staff row, and mark the token
   * used — all in one transaction.
   */
  async consumeInviteSignup(
    params: ConsumeInviteSignupParams,
  ): Promise<{ staffId: string; supabaseUid: string }> {
    const { token, password, name, dateOfBirth, mobileNumber } = params;

    return this.db.transaction().execute(async (trx) => {
      // a. Lock the invite row for the duration of the transaction.
      const invite = await trx
        .selectFrom('invite_links')
        .selectAll()
        .where('token', '=', token)
        .forUpdate()
        .executeTakeFirst();

      if (!invite) {
        throw new AuthError('INVITE_NOT_FOUND', 404, 'Invite not found.');
      }
      // b.
      if (invite.used_at !== null) {
        throw new AuthError('INVITE_ALREADY_USED', 409, 'This invite has already been used.');
      }
      // c.
      if (new Date(invite.expires_at as unknown as string).getTime() < Date.now()) {
        throw new AuthError('INVITE_EXPIRED', 410, 'This invite has expired.');
      }

      // d. H-04: refuse if a staff row already exists for this email, in ANY
      // state (including soft-deleted). Failing here avoids orphaning a freshly
      // created Supabase user against a staff row we can't insert.
      if (invite.email) {
        const existing = await trx
          .selectFrom('staff')
          .select('id')
          .where('email', '=', invite.email)
          .limit(1)
          .executeTakeFirst();
        if (existing) {
          throw new AuthError('ALREADY_PROCESSED', 409, 'This account has already been processed.');
        }
      }

      // e. The Supabase user was created at invite time (inviteUserByEmail).
      // Set its password and confirm the email — email_confirm: true means the
      // user can log in immediately; the invite email was the confirmation gate.
      if (!invite.supabase_uid) {
        // Should never happen for invites created via createInvite.
        throw new AuthError('INVITE_NOT_FOUND', 404, 'Invite is not linked to an account.');
      }
      const supabaseUid = invite.supabase_uid;
      const { error } = await this.supabaseAdmin.auth.admin.updateUserById(supabaseUid, {
        password,
        email_confirm: true,
        user_metadata: { name },
      });
      if (error) {
        throw new AuthError('SUPABASE_UPDATE_FAILED', 500, 'Could not finalize the user account.');
      }

      // Everything past this point can leave the Supabase user without a matching
      // staff row on failure (the transaction rolls back our rows, but the
      // external user persists). MVP: log loudly; Sprint 13 adds a janitor job.
      try {
        // f. Insert the staff row.
        const staff = await trx
          .insertInto('staff')
          .values({
            supabase_uid: supabaseUid,
            name,
            email: invite.email ?? '',
            role: invite.role,
            date_of_birth: dateOfBirth,
            mobile_number: mobileNumber,
            active: true,
            mfa_enrolled: false,
          })
          .returning(['id'])
          .executeTakeFirstOrThrow();

        // g. Mark the invite consumed.
        await trx
          .updateTable('invite_links')
          .set({ used_at: sql`NOW()`, used_by: staff.id })
          .where('id', '=', invite.id)
          .execute();

        // h. Audit.
        this.auditServiceLog({
          actorId: staff.id,
          entity: 'staff',
          entityId: staff.id,
          action: 'staff.create',
          after: { email: invite.email, role: invite.role, via: 'invite' },
          trx,
        });

        // i. Pre-warm the staff_lookup cache (same shape the auth plugin reads).
        try {
          await this.redis.set(
            staffCacheKey(supabaseUid),
            JSON.stringify({
              id: staff.id,
              supabase_uid: supabaseUid,
              name,
              email: invite.email ?? '',
              role: invite.role,
              active: true,
              mfa_enrolled: false,
              avatar_url: null,
            }),
            'EX',
            STAFF_CACHE_TTL_SECONDS,
          );
        } catch (err) {
          this.logger.warn({ err, supabaseUid }, 'consumeInviteSignup: cache pre-warm failed');
        }

        return { staffId: staff.id, supabaseUid };
      } catch (err) {
        this.logger.error(
          { err, supabaseUid, email: invite.email },
          'consumeInviteSignup: ORPHANED Supabase user — created in Supabase but staff insert failed',
        );
        throw err;
      }
    });
  }

  /**
   * Self-signup: record a pending signup_requests row, optionally stream the
   * applicant's CV to R2, and notify every admin. Whole thing runs in one
   * transaction so a failed CV upload (e.g. oversized file) leaves no row
   * behind. Duplicate emails are rejected per audit H-04.
   */
  async signupRequest(
    form: SignupRequestInput,
    cv?: CvUpload,
  ): Promise<{ requestId: string; status: 'pending' }> {
    // Defense in depth: the schema already excludes 'admin', but a hand-rolled
    // API call could smuggle it past validation. Never let it through here.
    if ((form.roleRequested as string) === 'admin') {
      throw new AuthError('INVALID_ROLE', 422, 'Admin cannot be self-requested.');
    }

    // Validate MIME up-front (cheap, from the part header) so we fail fast
    // without inserting a row or reading the stream.
    let cvExt: string | undefined;
    if (cv) {
      cvExt = CV_MIME_EXT[cv.mimetype];
      if (!cvExt) {
        throw new AuthError('INVALID_FILE_TYPE', 422, 'CV must be a PDF or Word document.');
      }
    }

    return this.db.transaction().execute(async (trx) => {
      // H-04 check #1 (fast path): any staff row with this email, in ANY state
      // (deleted_at NOT filtered) blocks a new request.
      const existingStaff = await trx
        .selectFrom('staff')
        .select('id')
        .where('email', '=', form.email)
        .limit(1)
        .executeTakeFirst();
      if (existingStaff) {
        throw new AuthError(
          'ALREADY_PROCESSED',
          409,
          'A request or account already exists for this email.',
        );
      }

      // Insert pending request. H-04 check #2 (race backstop): the partial
      // unique index idx_signup_requests_email_pending rejects a concurrent
      // second pending row with a 23505 unique violation.
      let requestId: string;
      try {
        const row = await trx
          .insertInto('signup_requests')
          .values({
            name: form.name,
            email: form.email,
            date_of_birth: form.dateOfBirth,
            mobile_number: form.mobileNumber,
            role_requested: form.roleRequested,
            message: form.message ?? null,
            google_uid: form.googleUid ?? null,
            status: 'pending',
          })
          .returning(['id'])
          .executeTakeFirstOrThrow();
        requestId = row.id;
      } catch (err) {
        if (isUniqueViolation(err)) {
          throw new AuthError(
            'ALREADY_PROCESSED',
            409,
            'A request or account already exists for this email.',
          );
        }
        throw err;
      }

      // Stream the CV straight to R2 — never buffered. lib-storage's Upload
      // handles multipart for large streams; a too-large stream surfaces the
      // multipart 5MB limit error, which rolls back this whole transaction.
      if (cv && cvExt) {
        const key = `cvs/requests/${requestId}/cv.${cvExt}`;
        const upload = new Upload({
          client: this.s3,
          params: {
            Bucket: this.r2Bucket,
            Key: key,
            Body: cv.stream,
            ContentType: cv.mimetype,
          },
        });
        await upload.done();

        await trx
          .updateTable('signup_requests')
          .set({ cv_file_key: key })
          .where('id', '=', requestId)
          .execute();
      }

      // Notify every active admin (placeholder until Sprint 2).
      const admins = await trx
        .selectFrom('staff')
        .select('id')
        .where('role', '=', 'admin')
        .where('active', '=', true)
        .where('deleted_at', 'is', null)
        .execute();
      for (const admin of admins) {
        this.notificationServiceCreate({
          recipientId: admin.id,
          type: 'signup_request',
          title: `New access request from ${form.name}`,
          data: { requestId, roleRequested: form.roleRequested },
        });
      }

      return { requestId, status: 'pending' as const };
    });
  }

  /**
   * Admin approves a pending signup request. In ONE transaction: create the
   * Supabase user (no password — they set it via the recovery link we email),
   * create the staff row, backfill the current attendance period (M-02), and
   * mark the request approved. If any step fails, all of it rolls back.
   */
  async approveSignupRequest(
    requestId: string,
    roleAssigned: Role,
    reviewerStaffId: string,
  ): Promise<{ staffId: string; supabaseUid: string; attendanceRowsCreated: number }> {
    const outcome = await this.db.transaction().execute(async (trx) => {
      // a. Lock the request row for the transaction.
      const row = await trx
        .selectFrom('signup_requests')
        .selectAll()
        .where('id', '=', requestId)
        .forUpdate()
        .executeTakeFirst();
      if (!row) {
        throw new AuthError('NOT_FOUND', 404, 'Signup request not found.');
      }
      if (row.status !== 'pending') {
        throw new AuthError('ALREADY_REVIEWED', 409, 'This request has already been reviewed.');
      }

      // b. H-04 backstop: a staff row may have appeared (any state) since the
      // request was filed. If so, mark this request rejected with an internal
      // note (committed by returning, not throwing) and signal the caller.
      const existing = await trx
        .selectFrom('staff')
        .select('id')
        .where('email', '=', row.email)
        .limit(1)
        .executeTakeFirst();
      if (existing) {
        await trx
          .updateTable('signup_requests')
          .set({
            status: 'rejected',
            rejection_note: 'Account already exists at approval time',
            reviewed_at: sql`NOW()`,
            reviewed_by: reviewerStaffId,
          })
          .where('id', '=', requestId)
          .execute();
        this.auditServiceLog({
          actorId: reviewerStaffId,
          actorSource: 'web',
          entity: 'signup_request',
          entityId: requestId,
          action: 'signup_request.reject',
          after: { reason: 'h04_account_exists' },
          trx,
        });
        return { kind: 'h04' as const };
      }

      // c. Create the Supabase user with no password; recovery link sets it.
      const { data, error } = await this.supabaseAdmin.auth.admin.createUser({
        email: row.email,
        email_confirm: true,
        user_metadata: { name: row.name },
      });
      if (error || !data?.user) {
        throw new AuthError('SUPABASE_CREATE_FAILED', 500, 'Could not create the user account.');
      }
      const supabaseUid = data.user.id;

      // Past this point a failure can orphan the Supabase user (our rows roll
      // back, the external user persists). MVP: log loudly; Sprint 13 janitor.
      try {
        // d. Create the staff row.
        const staff = await trx
          .insertInto('staff')
          .values({
            supabase_uid: supabaseUid,
            name: row.name,
            email: row.email,
            role: roleAssigned,
            date_of_birth: row.date_of_birth,
            mobile_number: row.mobile_number,
            active: true,
            mfa_enrolled: false,
          })
          .returning(['id'])
          .executeTakeFirstOrThrow();

        // e. M-02: backfill attendance in the SAME transaction.
        const attendanceRowsCreated = await this.attendance.backfillCurrentPeriod(staff.id, trx);

        // f. Mark the request approved.
        await trx
          .updateTable('signup_requests')
          .set({
            status: 'approved',
            role_assigned: roleAssigned,
            reviewed_at: sql`NOW()`,
            reviewed_by: reviewerStaffId,
          })
          .where('id', '=', requestId)
          .execute();

        // g. Password-setup (recovery) link — best effort; failure must not
        // abort an otherwise-successful approval.
        let resetLink: string | undefined;
        try {
          const link = await this.supabaseAdmin.auth.admin.generateLink({
            type: 'recovery',
            email: row.email,
          });
          if (link?.error) {
            this.logger.warn({ err: link.error, email: row.email }, 'approve: generateLink failed');
          } else {
            resetLink = link?.data?.properties?.action_link;
          }
        } catch (err) {
          this.logger.warn({ err, email: row.email }, 'approve: generateLink threw');
        }

        // h. Notify the new staff member (recipient = the row we just created).
        this.notificationServiceCreate({
          recipientId: staff.id,
          type: 'signup_approved',
          title: 'Your access request was approved',
          data: { resetLink },
        });

        // i. Audit.
        this.auditServiceLog({
          actorId: reviewerStaffId,
          actorSource: 'web',
          entity: 'signup_request',
          entityId: requestId,
          action: 'signup_request.approve',
          after: { staffId: staff.id, roleAssigned },
          trx,
        });

        return {
          kind: 'approved' as const,
          staffId: staff.id,
          supabaseUid,
          attendanceRowsCreated,
        };
      } catch (err) {
        this.logger.error(
          { err, supabaseUid, email: row.email },
          'approveSignupRequest: ORPHANED Supabase user — created but staff/backfill failed; rolled back',
        );
        throw err;
      }
    });

    if (outcome.kind === 'h04') {
      throw new AuthError('ALREADY_PROCESSED', 409, 'An account already exists for this email.');
    }
    return {
      staffId: outcome.staffId,
      supabaseUid: outcome.supabaseUid,
      attendanceRowsCreated: outcome.attendanceRowsCreated,
    };
  }

  /**
   * Admin rejects a pending signup request. Terminal: no Supabase user, no
   * staff row, no attendance. The internal `rejectionNote` is stored and
   * surfaced only in the audit log + admin views — never to the applicant.
   */
  async rejectSignupRequest(
    requestId: string,
    rejectionNote: string,
    publicRejectionMessage: string | undefined,
    reviewerStaffId: string,
  ): Promise<{ status: 'rejected' }> {
    return this.db.transaction().execute(async (trx) => {
      const row = await trx
        .selectFrom('signup_requests')
        .select(['id', 'status'])
        .where('id', '=', requestId)
        .forUpdate()
        .executeTakeFirst();
      if (!row) {
        throw new AuthError('NOT_FOUND', 404, 'Signup request not found.');
      }
      if (row.status !== 'pending') {
        throw new AuthError('ALREADY_REVIEWED', 409, 'This request has already been reviewed.');
      }

      await trx
        .updateTable('signup_requests')
        .set({
          status: 'rejected',
          rejection_note: rejectionNote,
          public_rejection_message: publicRejectionMessage ?? null,
          reviewed_at: sql`NOW()`,
          reviewed_by: reviewerStaffId,
        })
        .where('id', '=', requestId)
        .execute();

      // rejection_note goes into the audit trail (admins can read it); the
      // rejected applicant has no JWT and never sees the audit log.
      this.auditServiceLog({
        actorId: reviewerStaffId,
        actorSource: 'web',
        entity: 'signup_request',
        entityId: requestId,
        action: 'signup_request.reject',
        after: { rejectionNote, publicRejectionMessage: publicRejectionMessage ?? null },
        trx,
      });

      return { status: 'rejected' as const };
    });
  }
}

/** Postgres unique-violation (SQLSTATE 23505), however the driver surfaces it. */
function isUniqueViolation(err: unknown): boolean {
  return (
    typeof err === 'object' &&
    err !== null &&
    'code' in err &&
    (err as { code?: unknown }).code === '23505'
  );
}
