/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AttendanceLogs {
  date: Timestamp;
  day_type: Generated<string>;
  id: Generated<string>;
  period: string;
  present: Generated<boolean>;
  staff_id: string;
  updated_at: Timestamp | null;
  updated_by: string | null;
  version: Generated<number>;
  work_log: string | null;
}

export interface AuditLog {
  action: string;
  changed_by_source: Generated<string>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  ip_address: string | null;
  new_value: Json | null;
  old_value: Json | null;
  record_id: string | null;
  staff_id: string;
  table_name: string;
}

export interface BotSessions {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  last_activity_at: Generated<Timestamp>;
  staff_id: string;
}

export interface Clients {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  id: Generated<string>;
  is_internal: Generated<boolean>;
  name: string;
  pieces_per_visit: Generated<number>;
  shoot_slots_per_month: number;
  whatsapp_number: string | null;
}

export interface Comments {
  acknowledged_at: Timestamp | null;
  acknowledged_by: string | null;
  content: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  module: string;
  period: string;
  record_context: string;
  record_id: string;
  search_vector: Generated<string | null>;
  staff_id: string;
}

export interface ContentCalendar {
  client_id: string;
  date: Timestamp;
  id: Generated<string>;
  note: string | null;
  period: string;
  source: string | null;
  status: Generated<string>;
  updated_at: Timestamp | null;
  updated_by: string | null;
  version: Generated<number>;
}

export interface ContentPipelines {
  client_id: string;
  coming_shoot_date: Timestamp | null;
  coming_shoot_source: string | null;
  finals_ready_at: Timestamp | null;
  id: Generated<string>;
  last_shoot_date: Timestamp | null;
  period: string;
  posted_at: Timestamp | null;
  raw_received_at: Timestamp | null;
  updated_by: string | null;
  version: Generated<number>;
  visit_type: string | null;
}

export interface DashboardOrgStats {
  active_staff_count: Int8 | null;
  attendance_pct: Numeric | null;
  period: string | null;
}

export interface DashboardStaffTaskStats {
  period: string | null;
  staff_id: string | null;
  tasks_done: Int8 | null;
  tasks_overdue: Int8 | null;
  tasks_pending: Int8 | null;
  total_assigned: Int8 | null;
}

export interface Holidays {
  active: Generated<boolean>;
  added_by: string;
  created_at: Generated<Timestamp>;
  date: Timestamp;
  id: Generated<string>;
  name: string;
  period: string;
  removed_at: Timestamp | null;
  removed_by: string | null;
}

export interface InviteLinks {
  created_by: string;
  email: string | null;
  expires_at: Generated<Timestamp>;
  id: Generated<string>;
  role: string;
  token: Generated<string>;
  used_at: Timestamp | null;
  used_by: string | null;
}

export interface MessageMentions {
  message_id: string;
  staff_id: string;
}

export interface Messages {
  channel: string;
  content: string;
  content_type: Generated<string>;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  edited_at: Timestamp | null;
  id: Generated<string>;
  parent_id: string | null;
  search_vector: Generated<string | null>;
  sender_id: string | null;
  sender_type: Generated<string>;
}

export interface Months {
  created_at: Generated<Timestamp>;
  label: string;
  locked: Generated<boolean>;
  locked_at: Timestamp | null;
  locked_by: string | null;
  period: string;
  unlock_reason: string | null;
  unlocked_at: Timestamp | null;
  unlocked_by: string | null;
}

export interface Notifications {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_read: Generated<boolean>;
  message: string | null;
  payload: Generated<Json>;
  staff_id: string;
  title: string;
  type: string;
}

export interface PgStatStatements {
  blk_read_time: number | null;
  blk_write_time: number | null;
  calls: Int8 | null;
  dbid: number | null;
  jit_emission_count: Int8 | null;
  jit_emission_time: number | null;
  jit_functions: Int8 | null;
  jit_generation_time: number | null;
  jit_inlining_count: Int8 | null;
  jit_inlining_time: number | null;
  jit_optimization_count: Int8 | null;
  jit_optimization_time: number | null;
  local_blks_dirtied: Int8 | null;
  local_blks_hit: Int8 | null;
  local_blks_read: Int8 | null;
  local_blks_written: Int8 | null;
  max_exec_time: number | null;
  max_plan_time: number | null;
  mean_exec_time: number | null;
  mean_plan_time: number | null;
  min_exec_time: number | null;
  min_plan_time: number | null;
  plans: Int8 | null;
  query: string | null;
  queryid: Int8 | null;
  rows: Int8 | null;
  shared_blks_dirtied: Int8 | null;
  shared_blks_hit: Int8 | null;
  shared_blks_read: Int8 | null;
  shared_blks_written: Int8 | null;
  stddev_exec_time: number | null;
  stddev_plan_time: number | null;
  temp_blk_read_time: number | null;
  temp_blk_write_time: number | null;
  temp_blks_read: Int8 | null;
  temp_blks_written: Int8 | null;
  toplevel: boolean | null;
  total_exec_time: number | null;
  total_plan_time: number | null;
  userid: number | null;
  wal_bytes: Numeric | null;
  wal_fpi: Int8 | null;
  wal_records: Int8 | null;
}

export interface PgStatStatementsInfo {
  dealloc: Int8 | null;
  stats_reset: Timestamp | null;
}

export interface Reports {
  client_id: string | null;
  file_key: string;
  generated_at: Generated<Timestamp>;
  generated_by: string;
  id: Generated<string>;
  period: string;
  type: string;
}

export interface ShootSchedules {
  client_id: string;
  freelancer_id: string | null;
  id: Generated<string>;
  period: string;
  pieces_expected: Generated<number>;
  slot_date: Timestamp | null;
  slot_index: number;
  slot_status: Generated<string>;
  updated_at: Timestamp | null;
  updated_by: string | null;
}

export interface SignupRequests {
  created_at: Generated<Timestamp>;
  cv_file_key: string | null;
  date_of_birth: Timestamp;
  email: string;
  google_uid: string | null;
  id: Generated<string>;
  message: string | null;
  mobile_number: string;
  name: string;
  public_rejection_message: string | null;
  rejection_note: string | null;
  reviewed_at: Timestamp | null;
  reviewed_by: string | null;
  role_assigned: string | null;
  role_requested: string;
  status: Generated<string>;
}

export interface Staff {
  active: Generated<boolean>;
  avatar_url: string | null;
  created_at: Generated<Timestamp>;
  cv_file_key: string | null;
  date_of_birth: Timestamp | null;
  deleted_at: Timestamp | null;
  email: string;
  id: Generated<string>;
  mfa_enrolled: Generated<boolean>;
  mobile_number: string | null;
  name: string;
  push_platform: string | null;
  push_token: string | null;
  role: string;
  supabase_uid: string | null;
}

export interface TaskAssignees {
  assigned_at: Generated<Timestamp>;
  assigned_by: string | null;
  staff_id: string;
  task_id: string;
}

export interface TaskAttachments {
  file_key: string;
  file_name: string;
  file_size: Int8;
  id: Generated<string>;
  mime_type: string | null;
  task_id: string;
  uploaded_at: Generated<Timestamp>;
  uploaded_by: string;
}

export interface Tasks {
  client_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  date: Timestamp;
  deadline: Timestamp | null;
  deleted_at: Timestamp | null;
  dependency_id: string | null;
  description: string;
  id: Generated<string>;
  period: string;
  priority: string | null;
  remark: string | null;
  result: string | null;
  search_vector: Generated<string | null>;
  status: Generated<string>;
}

export interface TaskTimeLogs {
  created_at: Generated<Timestamp>;
  ended_at: Timestamp | null;
  id: Generated<string>;
  manual_mins: number | null;
  staff_id: string;
  started_at: Timestamp | null;
  task_id: string;
}

export interface UserPermissions {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  permission_key: string;
  set_by: string | null;
  staff_id: string;
  value: boolean;
}

export interface DB {
  attendance_logs: AttendanceLogs;
  audit_log: AuditLog;
  bot_sessions: BotSessions;
  clients: Clients;
  comments: Comments;
  content_calendar: ContentCalendar;
  content_pipelines: ContentPipelines;
  dashboard_org_stats: DashboardOrgStats;
  dashboard_staff_task_stats: DashboardStaffTaskStats;
  holidays: Holidays;
  invite_links: InviteLinks;
  message_mentions: MessageMentions;
  messages: Messages;
  months: Months;
  notifications: Notifications;
  pg_stat_statements: PgStatStatements;
  pg_stat_statements_info: PgStatStatementsInfo;
  reports: Reports;
  shoot_schedules: ShootSchedules;
  signup_requests: SignupRequests;
  staff: Staff;
  task_assignees: TaskAssignees;
  task_attachments: TaskAttachments;
  task_time_logs: TaskTimeLogs;
  tasks: Tasks;
  user_permissions: UserPermissions;
}
