// Shared Zod schemas and TypeScript types live here.
// Filled in incrementally per sprint (Sprint 2 onward).

// Kysely DB types, generated by kysely-codegen (apps/api db:codegen).
export type * from './db.types';

// Cross-cutting constants shared by API + web.
export { SYSTEM_ACTOR_UUID } from './constants/system';
export { ROLE_DEFAULTS } from './constants/permissions';
export type { RolePermissionDefaults, PermissionKey } from './constants/permissions';
export {
  ATTACHMENT_MAX_BYTES,
  TASK_ATTACHMENT_TOTAL_BYTES,
  ATTACHMENT_MIME_ALLOWLIST,
} from './constants/attachments';
export type { AttachmentMime } from './constants/attachments';

// Work Allocation (tasks) request schemas — shared by API validation + web forms.
export {
  TASK_STATUS_VALUES,
  TASK_PRIORITY_VALUES,
  TaskStatusSchema,
  TaskPrioritySchema,
  TaskQuerySchema,
  TaskCreateSchema,
  TaskUpdateSchema,
  AssignSchema,
  AttachmentPresignSchema,
  AttachmentConfirmSchema,
} from './schemas/tasks';
export type {
  TaskQuery,
  TaskCreateBody,
  TaskUpdateBody,
  AssignBody,
  AttachmentPresignBody,
  AttachmentConfirmBody,
} from './schemas/tasks';

// Shoot Planner request schemas — shared by API validation + web forms.
export {
  SLOT_STATUS_VALUES,
  SlotStatusSchema,
  ShootQuerySchema,
  SlotUpdateSchema,
  SlotResetSchema,
  SlotCountSchema,
} from './schemas/shoot-planner';
export type {
  ShootQuery,
  SlotUpdateBody,
  SlotResetBody,
  SlotCountBody,
} from './schemas/shoot-planner';

// Content Dropper request schemas — shared by API validation + web forms.
export {
  STAGE_VALUES,
  StageSchema,
  DropperQuerySchema,
  StageUpdateSchema,
} from './schemas/content-dropper';
export type {
  DropperQuery,
  StageUpdateBody,
} from './schemas/content-dropper';

// Client request schemas — shared by API validation + web forms.
export { ClientNameSchema, ClientCreateSchema } from './schemas/clients';
export type { ClientNameBody, ClientCreateBody, ClientCreateInput } from './schemas/clients';

// Content Calendar — status vocabulary + request schemas (API + web dropdown).
export {
  CALENDAR_STATUSES,
  CALENDAR_NOTE_MAX,
  CalendarStatusSchema,
  CalendarQuerySchema,
  CellUpdateBase,
  CellUpdateSchema,
} from './schemas/content-calendar';
export type { CalendarStatus, CalendarQuery, CellUpdateBody } from './schemas/content-calendar';
