name: Deploy API
on: { push: { branches: [main] } }
jobs:
  migrate-prod-db:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with: { node-version: 22, cache: pnpm }
      - run: pnpm install --frozen-lockfile
      - run: pnpm --filter @skaly/api db:migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_PROD }}
